ut/nvmf: add stub for mdns_tgt_stop_mdns_prr()
Some linkers complain about it being missing:

nvmf_ut.o: in function `nvmf_tgt_destroy_cb':
nvmf_ut.c:(.text.nvmf_tgt_destroy_cb[nvmf_tgt_destroy_cb]+0x1d8): undefined reference to `nvmf_tgt_stop_mdns_prr'

Signed-off-by: Konrad Sztyber <konrad.sztyber@intel.com>
Change-Id: Ifcf44612cd2b73cd6b5c93ea0b746d438f18c159
Reviewed-on: https://review.spdk.io/gerrit/c/spdk/spdk/+/24471
Tested-by: SPDK CI Jenkins <sys_sgci@intel.com>
Reviewed-by: Aleksey Marchuk <alexeymar@nvidia.com>
Community-CI: Mellanox Build Bot
Reviewed-by: Jim Harris <jim.harris@samsung.com>